# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramViewer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramViewer
  pod 'InstagramKit', '~> 3.0'
  pod 'InstagramKit/UICKeyChainStore'
  pod 'AFNetworking'
  pod 'Realm'
end
